services:
  - type: web
    name: wordpress
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: WORDPRESS_DB_HOST
        value: mariadb:3306
      - key: WORDPRESS_DB_NAME
        value: wordpress
      - key: WORDPRESS_DB_USER
        value: wpuser
      - key: WORDPRESS_DB_PASSWORD
        value: wp_pass
    ports:
      - 80

  - type: web
    name: mariadb
    env: docker
    plan: free
    dockerfilePath: ./mariadb.Dockerfile
    envVars:
      - key: MARIADB_DATABASE
        value: wordpress
      - key: MARIADB_USER
        value: wpuser
      - key: MARIADB_PASSWORD
        value: wp_pass
      - key: MARIADB_ROOT_PASSWORD
        value: root_pass
    ports:
      - 3306
